kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: janwillies-preprod-view
  namespace: preprod # This binding only applies in the "testing" namespace
subjects:
  - kind: User # May be "User", "Group" or "ServiceAccount"
    name: janwillies
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io